// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23GW0lj0eaujAeAlXw1mTBuBxIE2OofY',
    appId: '1:876880650082:web:de5dd6d6d04f4d2be3d63b',
    messagingSenderId: '876880650082',
    projectId: 'dishedout-6fdf2',
    authDomain: 'dishedout-6fdf2.firebaseapp.com',
    storageBucket: 'dishedout-6fdf2.firebasestorage.app',
    measurementId: 'G-8V9MQKZ514',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFSymV95xhDHh2sBMuhlTFaFFzK5YoSlc',
    appId: '1:876880650082:android:4d9b89b745fb9b27e3d63b',
    messagingSenderId: '876880650082',
    projectId: 'dishedout-6fdf2',
    storageBucket: 'dishedout-6fdf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1KCYWKrAUMffyUUCyloDC2oSTwWXHZo',
    appId: '1:876880650082:ios:6b706ac0d0bbe173e3d63b',
    messagingSenderId: '876880650082',
    projectId: 'dishedout-6fdf2',
    storageBucket: 'dishedout-6fdf2.firebasestorage.app',
    androidClientId: '876880650082-0sdbhopi5if079anba8uikprn31eruq7.apps.googleusercontent.com',
    iosClientId: '876880650082-jq2g7fie5gmnva82gf0uk9qbe9vf6qqq.apps.googleusercontent.com',
    iosBundleId: 'com.dishedout.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1KCYWKrAUMffyUUCyloDC2oSTwWXHZo',
    appId: '1:876880650082:ios:5bf96854897100d6e3d63b',
    messagingSenderId: '876880650082',
    projectId: 'dishedout-6fdf2',
    storageBucket: 'dishedout-6fdf2.firebasestorage.app',
    iosBundleId: 'com.example.foodle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC23GW0lj0eaujAeAlXw1mTBuBxIE2OofY',
    appId: '1:876880650082:web:d2959ddbe1ff1f01e3d63b',
    messagingSenderId: '876880650082',
    projectId: 'dishedout-6fdf2',
    authDomain: 'dishedout-6fdf2.firebaseapp.com',
    storageBucket: 'dishedout-6fdf2.firebasestorage.app',
    measurementId: 'G-1BMQ72YKLP',
  );
}